/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_project_aek_cvcamera_MangaEffect */

#ifndef _Included_com_project_aek_cvcamera_MangaEffect
#define _Included_com_project_aek_cvcamera_MangaEffect
#ifdef __cplusplus
extern "C" {
#endif
#undef com_project_aek_cvcamera_MangaEffect_SKETCH
#define com_project_aek_cvcamera_MangaEffect_SKETCH 0L
#undef com_project_aek_cvcamera_MangaEffect_SKETCH_C
#define com_project_aek_cvcamera_MangaEffect_SKETCH_C 1L
#undef com_project_aek_cvcamera_MangaEffect_EVIL
#define com_project_aek_cvcamera_MangaEffect_EVIL 2L
/*
 * Class:     com_project_aek_cvcamera_MangaEffect
 * Method:    CartoonifyImage
 * Signature: (JJII)V
 */
JNIEXPORT void JNICALL Java_com_project_aek_cvcamera_MangaEffect_CartoonifyImage
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_project_aek_cvcamera_MangaEffect
 * Method:    setCaptureFrame
 * Signature: (II[B[IZ)V
 */
JNIEXPORT void JNICALL Java_com_project_aek_cvcamera_MangaEffect_setCaptureFrame
(JNIEnv *, jobject, jint, jint, jbyteArray, jintArray, jboolean);

JNIEXPORT void JNICALL Java_com_project_aek_cvcamera_MangaEffect_Cartoonify
(JNIEnv *, jobject, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
